
#ifndef _XDKSTD_H
#define _XDKSTD_H

#include "xdkdef.h"
#include "xdkinit.h"
#include "dlink.h"
#include "gdiattr.h"
#include "fontutil.h"
#include "clrutil.h"
#include "str.h"
#include "strutil.h"
#include "optparser.h"
#include "der.h"
#include "base64.h"
#include "conv.h"
#include "money.h"
#include "solarterms.h"

#include "hashtable.h"
#include "dicttable.h"
#include "stacktable.h"
#include "stringtable.h"
#include "stringarray.h"
#include "integerarray.h"
#include "numericarray.h"
#include "wordstable.h"
#include "actable.h"
#include "varobj.h"
#include "varbytes.h"
#include "variant.h"
#include "varstr.h"
#include "message.h"
#include "queue.h"
#include "linear.h"
#include "spinlock.h"
#include "multitree.h"
#include "bplustree.h"
#include "binatree.h"
#include "trietree.h"
#include "filetable.h"
#include "escape.h"
#include "expres.h"
#include "macro.h"
#include "nuid.h"
#include "prim.h"
#include "sort.h"
#include "bioinf.h"
#include "stream.h"
#include "loginf.h"

#include "set.h"
#include "vector.h"
#include "matrix.h"
#include "map.h"

#endif //_XDKINC_H
